// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Nichelson.Test")>]
[<assembly: AssemblyProductAttribute("Nichelson")>]
[<assembly: AssemblyVersionAttribute("0.0.16")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-02-09T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.16")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.16")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","e709bb43f1c2f651644bd857e86f0fd99ee988df")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Nichelson.Test"
    let [<Literal>] AssemblyProduct = "Nichelson"
    let [<Literal>] AssemblyVersion = "0.0.16"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-02-09T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.0.16"
    let [<Literal>] AssemblyInformationalVersion = "0.0.16"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "e709bb43f1c2f651644bd857e86f0fd99ee988df"
