// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Nichelson")>]
[<assembly: AssemblyProductAttribute("Nichelson")>]
[<assembly: AssemblyVersionAttribute("0.0.16")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2021-02-09T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.16")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.16")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","2375772620b4cb14cafd95b60827a762cbe2da5d")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Nichelson"
    let [<Literal>] AssemblyProduct = "Nichelson"
    let [<Literal>] AssemblyVersion = "0.0.16"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2021-02-09T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.0.16"
    let [<Literal>] AssemblyInformationalVersion = "0.0.16"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "2375772620b4cb14cafd95b60827a762cbe2da5d"
